// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.24.4
// source: Connection.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloseCode int32

const (
	CloseCode_CLOSE_CODE_UNSPECIFIED           CloseCode = 0
	CloseCode_CLOSE_CODE_NORMAL                CloseCode = 1006
	CloseCode_CLOSE_CODE_UNAUTHORIZED          CloseCode = 4401
	CloseCode_CLOSE_CODE_NOTFOUND              CloseCode = 4404
	CloseCode_CLOSE_CODE_CLIENT_USER_REQUESTED CloseCode = 4100
	CloseCode_CLOSE_CODE_ROOM_EXPIRED          CloseCode = 4001
)

// Enum value maps for CloseCode.
var (
	CloseCode_name = map[int32]string{
		0:    "CLOSE_CODE_UNSPECIFIED",
		1006: "CLOSE_CODE_NORMAL",
		4401: "CLOSE_CODE_UNAUTHORIZED",
		4404: "CLOSE_CODE_NOTFOUND",
		4100: "CLOSE_CODE_CLIENT_USER_REQUESTED",
		4001: "CLOSE_CODE_ROOM_EXPIRED",
	}
	CloseCode_value = map[string]int32{
		"CLOSE_CODE_UNSPECIFIED":           0,
		"CLOSE_CODE_NORMAL":                1006,
		"CLOSE_CODE_UNAUTHORIZED":          4401,
		"CLOSE_CODE_NOTFOUND":              4404,
		"CLOSE_CODE_CLIENT_USER_REQUESTED": 4100,
		"CLOSE_CODE_ROOM_EXPIRED":          4001,
	}
)

func (x CloseCode) Enum() *CloseCode {
	p := new(CloseCode)
	*p = x
	return p
}

func (x CloseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_Connection_proto_enumTypes[0].Descriptor()
}

func (CloseCode) Type() protoreflect.EnumType {
	return &file_Connection_proto_enumTypes[0]
}

func (x CloseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloseCode.Descriptor instead.
func (CloseCode) EnumDescriptor() ([]byte, []int) {
	return file_Connection_proto_rawDescGZIP(), []int{0}
}

var File_Connection_proto protoreflect.FileDescriptor

var file_Connection_proto_rawDesc = []byte{
	0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2a, 0xbc, 0x01, 0x0a, 0x09, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1a, 0x0a, 0x16, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x11,
	0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4e, 0x4f, 0x52, 0x4d, 0x41,
	0x4c, 0x10, 0xee, 0x07, 0x12, 0x1c, 0x0a, 0x17, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x43, 0x4f,
	0x44, 0x45, 0x5f, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44, 0x10,
	0xb1, 0x22, 0x12, 0x18, 0x0a, 0x13, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x43, 0x4f, 0x44, 0x45,
	0x5f, 0x4e, 0x4f, 0x54, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0xb4, 0x22, 0x12, 0x25, 0x0a, 0x20,
	0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e,
	0x54, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x45, 0x44,
	0x10, 0x84, 0x20, 0x12, 0x1c, 0x0a, 0x17, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x43, 0x4f, 0x44,
	0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0xa1,
	0x1f, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_Connection_proto_rawDescOnce sync.Once
	file_Connection_proto_rawDescData = file_Connection_proto_rawDesc
)

func file_Connection_proto_rawDescGZIP() []byte {
	file_Connection_proto_rawDescOnce.Do(func() {
		file_Connection_proto_rawDescData = protoimpl.X.CompressGZIP(file_Connection_proto_rawDescData)
	})
	return file_Connection_proto_rawDescData
}

var file_Connection_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Connection_proto_goTypes = []interface{}{
	(CloseCode)(0), // 0: CloseCode
}
var file_Connection_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Connection_proto_init() }
func file_Connection_proto_init() {
	if File_Connection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Connection_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Connection_proto_goTypes,
		DependencyIndexes: file_Connection_proto_depIdxs,
		EnumInfos:         file_Connection_proto_enumTypes,
	}.Build()
	File_Connection_proto = out.File
	file_Connection_proto_rawDesc = nil
	file_Connection_proto_goTypes = nil
	file_Connection_proto_depIdxs = nil
}
