// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.24.4
// source: Pointer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pointer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointerType PointerType  `protobuf:"varint,1,opt,name=pointerType,proto3,enum=PointerType" json:"pointerType,omitempty"`
	Coordinates *Coordinates `protobuf:"bytes,2,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *Pointer) Reset() {
	*x = Pointer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Pointer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pointer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pointer) ProtoMessage() {}

func (x *Pointer) ProtoReflect() protoreflect.Message {
	mi := &file_Pointer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pointer.ProtoReflect.Descriptor instead.
func (*Pointer) Descriptor() ([]byte, []int) {
	return file_Pointer_proto_rawDescGZIP(), []int{0}
}

func (x *Pointer) GetPointerType() PointerType {
	if x != nil {
		return x.PointerType
	}
	return PointerType_POINTER_TYPE_UNSPECIFIED
}

func (x *Pointer) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type PointerCollection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pointers []*Pointer `protobuf:"bytes,1,rep,name=pointers,proto3" json:"pointers,omitempty"`
}

func (x *PointerCollection) Reset() {
	*x = PointerCollection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Pointer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PointerCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointerCollection) ProtoMessage() {}

func (x *PointerCollection) ProtoReflect() protoreflect.Message {
	mi := &file_Pointer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointerCollection.ProtoReflect.Descriptor instead.
func (*PointerCollection) Descriptor() ([]byte, []int) {
	return file_Pointer_proto_rawDescGZIP(), []int{1}
}

func (x *PointerCollection) GetPointers() []*Pointer {
	if x != nil {
		return x.Pointers
	}
	return nil
}

var File_Pointer_proto protoreflect.FileDescriptor

var file_Pointer_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x11, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x69, 0x0a, 0x07, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x2e, 0x0a,
	0x0b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a,
	0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x22, 0x39, 0x0a,
	0x11, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x08, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x08,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Pointer_proto_rawDescOnce sync.Once
	file_Pointer_proto_rawDescData = file_Pointer_proto_rawDesc
)

func file_Pointer_proto_rawDescGZIP() []byte {
	file_Pointer_proto_rawDescOnce.Do(func() {
		file_Pointer_proto_rawDescData = protoimpl.X.CompressGZIP(file_Pointer_proto_rawDescData)
	})
	return file_Pointer_proto_rawDescData
}

var file_Pointer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Pointer_proto_goTypes = []interface{}{
	(*Pointer)(nil),           // 0: Pointer
	(*PointerCollection)(nil), // 1: PointerCollection
	(PointerType)(0),          // 2: PointerType
	(*Coordinates)(nil),       // 3: Coordinates
}
var file_Pointer_proto_depIdxs = []int32{
	2, // 0: Pointer.pointerType:type_name -> PointerType
	3, // 1: Pointer.coordinates:type_name -> Coordinates
	0, // 2: PointerCollection.pointers:type_name -> Pointer
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Pointer_proto_init() }
func file_Pointer_proto_init() {
	if File_Pointer_proto != nil {
		return
	}
	file_CommonTypes_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Pointer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pointer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Pointer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PointerCollection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Pointer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Pointer_proto_goTypes,
		DependencyIndexes: file_Pointer_proto_depIdxs,
		MessageInfos:      file_Pointer_proto_msgTypes,
	}.Build()
	File_Pointer_proto = out.File
	file_Pointer_proto_rawDesc = nil
	file_Pointer_proto_goTypes = nil
	file_Pointer_proto_depIdxs = nil
}
