// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.24.4
// source: Server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerMessageType int32

const (
	ServerMessageType_SERVER_MESSAGE_UNSPECIFIED ServerMessageType = 0
	ServerMessageType_RELAY                      ServerMessageType = 1
)

// Enum value maps for ServerMessageType.
var (
	ServerMessageType_name = map[int32]string{
		0: "SERVER_MESSAGE_UNSPECIFIED",
		1: "RELAY",
	}
	ServerMessageType_value = map[string]int32{
		"SERVER_MESSAGE_UNSPECIFIED": 0,
		"RELAY":                      1,
	}
)

func (x ServerMessageType) Enum() *ServerMessageType {
	p := new(ServerMessageType)
	*p = x
	return p
}

func (x ServerMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_Server_proto_enumTypes[0].Descriptor()
}

func (ServerMessageType) Type() protoreflect.EnumType {
	return &file_Server_proto_enumTypes[0]
}

func (x ServerMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerMessageType.Descriptor instead.
func (ServerMessageType) EnumDescriptor() ([]byte, []int) {
	return file_Server_proto_rawDescGZIP(), []int{0}
}

type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ServerMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=ServerMessageType" json:"type,omitempty"`
	// Types that are assignable to Message:
	//
	//	*ServerMessage_Relay
	Message isServerMessage_Message `protobuf_oneof:"message"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_Server_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMessage) GetType() ServerMessageType {
	if x != nil {
		return x.Type
	}
	return ServerMessageType_SERVER_MESSAGE_UNSPECIFIED
}

func (m *ServerMessage) GetMessage() isServerMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ServerMessage) GetRelay() *ClientMessage {
	if x, ok := x.GetMessage().(*ServerMessage_Relay); ok {
		return x.Relay
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_Relay struct {
	Relay *ClientMessage `protobuf:"bytes,2,opt,name=relay,proto3,oneof"`
}

func (*ServerMessage_Relay) isServerMessage_Message() {}

var File_Server_proto protoreflect.FileDescriptor

var file_Server_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x0d,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x42, 0x09, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x3e, 0x0a, 0x11, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x1a, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x52, 0x45, 0x4c, 0x41, 0x59, 0x10, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Server_proto_rawDescOnce sync.Once
	file_Server_proto_rawDescData = file_Server_proto_rawDesc
)

func file_Server_proto_rawDescGZIP() []byte {
	file_Server_proto_rawDescOnce.Do(func() {
		file_Server_proto_rawDescData = protoimpl.X.CompressGZIP(file_Server_proto_rawDescData)
	})
	return file_Server_proto_rawDescData
}

var file_Server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Server_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Server_proto_goTypes = []interface{}{
	(ServerMessageType)(0), // 0: ServerMessageType
	(*ServerMessage)(nil),  // 1: ServerMessage
	(*ClientMessage)(nil),  // 2: ClientMessage
}
var file_Server_proto_depIdxs = []int32{
	0, // 0: ServerMessage.type:type_name -> ServerMessageType
	2, // 1: ServerMessage.relay:type_name -> ClientMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Server_proto_init() }
func file_Server_proto_init() {
	if File_Server_proto != nil {
		return
	}
	file_Client_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_Server_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ServerMessage_Relay)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Server_proto_goTypes,
		DependencyIndexes: file_Server_proto_depIdxs,
		EnumInfos:         file_Server_proto_enumTypes,
		MessageInfos:      file_Server_proto_msgTypes,
	}.Build()
	File_Server_proto = out.File
	file_Server_proto_rawDesc = nil
	file_Server_proto_goTypes = nil
	file_Server_proto_depIdxs = nil
}
