// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.24.4
// source: Swifteams.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// COMMON TYPES
type PointerType int32

const (
	PointerType_POINTER_TYPE_UNSPECIFIED PointerType = 0
	PointerType_POINTER_TYPE_POINTER     PointerType = 1
	PointerType_POINTER_TYPE_CURSOR      PointerType = 2
	PointerType_POINTER_TYPE_TOUCH       PointerType = 3
)

// Enum value maps for PointerType.
var (
	PointerType_name = map[int32]string{
		0: "POINTER_TYPE_UNSPECIFIED",
		1: "POINTER_TYPE_POINTER",
		2: "POINTER_TYPE_CURSOR",
		3: "POINTER_TYPE_TOUCH",
	}
	PointerType_value = map[string]int32{
		"POINTER_TYPE_UNSPECIFIED": 0,
		"POINTER_TYPE_POINTER":     1,
		"POINTER_TYPE_CURSOR":      2,
		"POINTER_TYPE_TOUCH":       3,
	}
)

func (x PointerType) Enum() *PointerType {
	p := new(PointerType)
	*p = x
	return p
}

func (x PointerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PointerType) Descriptor() protoreflect.EnumDescriptor {
	return file_Swifteams_proto_enumTypes[0].Descriptor()
}

func (PointerType) Type() protoreflect.EnumType {
	return &file_Swifteams_proto_enumTypes[0]
}

func (x PointerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PointerType.Descriptor instead.
func (PointerType) EnumDescriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{0}
}

// STORE
type StoreMemberType int32

const (
	StoreMemberType_MEMBER_UNSPECIFIED StoreMemberType = 0
	StoreMemberType_STRING             StoreMemberType = 1
	StoreMemberType_NUMBER             StoreMemberType = 2
	StoreMemberType_BOOLEAN            StoreMemberType = 5
	StoreMemberType_TIMESTAMP          StoreMemberType = 6
	StoreMemberType_COORDINATE         StoreMemberType = 3
	StoreMemberType_USER               StoreMemberType = 4
)

// Enum value maps for StoreMemberType.
var (
	StoreMemberType_name = map[int32]string{
		0: "MEMBER_UNSPECIFIED",
		1: "STRING",
		2: "NUMBER",
		5: "BOOLEAN",
		6: "TIMESTAMP",
		3: "COORDINATE",
		4: "USER",
	}
	StoreMemberType_value = map[string]int32{
		"MEMBER_UNSPECIFIED": 0,
		"STRING":             1,
		"NUMBER":             2,
		"BOOLEAN":            5,
		"TIMESTAMP":          6,
		"COORDINATE":         3,
		"USER":               4,
	}
)

func (x StoreMemberType) Enum() *StoreMemberType {
	p := new(StoreMemberType)
	*p = x
	return p
}

func (x StoreMemberType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoreMemberType) Descriptor() protoreflect.EnumDescriptor {
	return file_Swifteams_proto_enumTypes[1].Descriptor()
}

func (StoreMemberType) Type() protoreflect.EnumType {
	return &file_Swifteams_proto_enumTypes[1]
}

func (x StoreMemberType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoreMemberType.Descriptor instead.
func (StoreMemberType) EnumDescriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{1}
}

type StoreAccessType int32

const (
	StoreAccessType_ACCESS_UNSPECIFIED StoreAccessType = 0
	StoreAccessType_PUBLIC             StoreAccessType = 1
	StoreAccessType_PRODUCER           StoreAccessType = 2
	StoreAccessType_HOST               StoreAccessType = 3
)

// Enum value maps for StoreAccessType.
var (
	StoreAccessType_name = map[int32]string{
		0: "ACCESS_UNSPECIFIED",
		1: "PUBLIC",
		2: "PRODUCER",
		3: "HOST",
	}
	StoreAccessType_value = map[string]int32{
		"ACCESS_UNSPECIFIED": 0,
		"PUBLIC":             1,
		"PRODUCER":           2,
		"HOST":               3,
	}
)

func (x StoreAccessType) Enum() *StoreAccessType {
	p := new(StoreAccessType)
	*p = x
	return p
}

func (x StoreAccessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoreAccessType) Descriptor() protoreflect.EnumDescriptor {
	return file_Swifteams_proto_enumTypes[2].Descriptor()
}

func (StoreAccessType) Type() protoreflect.EnumType {
	return &file_Swifteams_proto_enumTypes[2]
}

func (x StoreAccessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoreAccessType.Descriptor instead.
func (StoreAccessType) EnumDescriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{2}
}

type StorePersistenceType int32

const (
	StorePersistenceType_PERSISTENCE_UNSPECIFIED StorePersistenceType = 0
	StorePersistenceType_NONE                    StorePersistenceType = 1
	StorePersistenceType_PREFERRED               StorePersistenceType = 2
	StorePersistenceType_REQUIRED                StorePersistenceType = 3
)

// Enum value maps for StorePersistenceType.
var (
	StorePersistenceType_name = map[int32]string{
		0: "PERSISTENCE_UNSPECIFIED",
		1: "NONE",
		2: "PREFERRED",
		3: "REQUIRED",
	}
	StorePersistenceType_value = map[string]int32{
		"PERSISTENCE_UNSPECIFIED": 0,
		"NONE":                    1,
		"PREFERRED":               2,
		"REQUIRED":                3,
	}
)

func (x StorePersistenceType) Enum() *StorePersistenceType {
	p := new(StorePersistenceType)
	*p = x
	return p
}

func (x StorePersistenceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorePersistenceType) Descriptor() protoreflect.EnumDescriptor {
	return file_Swifteams_proto_enumTypes[3].Descriptor()
}

func (StorePersistenceType) Type() protoreflect.EnumType {
	return &file_Swifteams_proto_enumTypes[3]
}

func (x StorePersistenceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorePersistenceType.Descriptor instead.
func (StorePersistenceType) EnumDescriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{3}
}

// USER
type UserSubscriptionType int32

const (
	UserSubscriptionType_USER_SUBSCRIPTION_UNSPECIFIED UserSubscriptionType = 0
	UserSubscriptionType_USER_SUBSCRIPTION_FREE        UserSubscriptionType = 1
	UserSubscriptionType_USER_SUBSCRIPTION_PREMIUM     UserSubscriptionType = 2
)

// Enum value maps for UserSubscriptionType.
var (
	UserSubscriptionType_name = map[int32]string{
		0: "USER_SUBSCRIPTION_UNSPECIFIED",
		1: "USER_SUBSCRIPTION_FREE",
		2: "USER_SUBSCRIPTION_PREMIUM",
	}
	UserSubscriptionType_value = map[string]int32{
		"USER_SUBSCRIPTION_UNSPECIFIED": 0,
		"USER_SUBSCRIPTION_FREE":        1,
		"USER_SUBSCRIPTION_PREMIUM":     2,
	}
)

func (x UserSubscriptionType) Enum() *UserSubscriptionType {
	p := new(UserSubscriptionType)
	*p = x
	return p
}

func (x UserSubscriptionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserSubscriptionType) Descriptor() protoreflect.EnumDescriptor {
	return file_Swifteams_proto_enumTypes[4].Descriptor()
}

func (UserSubscriptionType) Type() protoreflect.EnumType {
	return &file_Swifteams_proto_enumTypes[4]
}

func (x UserSubscriptionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserSubscriptionType.Descriptor instead.
func (UserSubscriptionType) EnumDescriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{4}
}

type ClientRole int32

const (
	ClientRole_CLIENT_ROLE_UNSPECIFIED ClientRole = 0
	ClientRole_GUEST                   ClientRole = 1
	ClientRole_ROOM_OWNER              ClientRole = 2
	ClientRole_SERVER_ADMIN            ClientRole = 3
)

// Enum value maps for ClientRole.
var (
	ClientRole_name = map[int32]string{
		0: "CLIENT_ROLE_UNSPECIFIED",
		1: "GUEST",
		2: "ROOM_OWNER",
		3: "SERVER_ADMIN",
	}
	ClientRole_value = map[string]int32{
		"CLIENT_ROLE_UNSPECIFIED": 0,
		"GUEST":                   1,
		"ROOM_OWNER":              2,
		"SERVER_ADMIN":            3,
	}
)

func (x ClientRole) Enum() *ClientRole {
	p := new(ClientRole)
	*p = x
	return p
}

func (x ClientRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientRole) Descriptor() protoreflect.EnumDescriptor {
	return file_Swifteams_proto_enumTypes[5].Descriptor()
}

func (ClientRole) Type() protoreflect.EnumType {
	return &file_Swifteams_proto_enumTypes[5]
}

func (x ClientRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientRole.Descriptor instead.
func (ClientRole) EnumDescriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{5}
}

type ClientMessageType int32

const (
	ClientMessageType_CLIENT_MESSAGE_TYPE_UNSPECIFIED ClientMessageType = 0
	ClientMessageType_UPDATE_NICKNAME                 ClientMessageType = 1
	ClientMessageType_UPDATE_POINTERS                 ClientMessageType = 2
	ClientMessageType_CHAT_MESSAGE                    ClientMessageType = 3
)

// Enum value maps for ClientMessageType.
var (
	ClientMessageType_name = map[int32]string{
		0: "CLIENT_MESSAGE_TYPE_UNSPECIFIED",
		1: "UPDATE_NICKNAME",
		2: "UPDATE_POINTERS",
		3: "CHAT_MESSAGE",
	}
	ClientMessageType_value = map[string]int32{
		"CLIENT_MESSAGE_TYPE_UNSPECIFIED": 0,
		"UPDATE_NICKNAME":                 1,
		"UPDATE_POINTERS":                 2,
		"CHAT_MESSAGE":                    3,
	}
)

func (x ClientMessageType) Enum() *ClientMessageType {
	p := new(ClientMessageType)
	*p = x
	return p
}

func (x ClientMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_Swifteams_proto_enumTypes[6].Descriptor()
}

func (ClientMessageType) Type() protoreflect.EnumType {
	return &file_Swifteams_proto_enumTypes[6]
}

func (x ClientMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientMessageType.Descriptor instead.
func (ClientMessageType) EnumDescriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{6}
}

// CONNECTION
type CloseCode int32

const (
	CloseCode_CLOSE_CODE_UNSPECIFIED           CloseCode = 0
	CloseCode_CLOSE_CODE_NORMAL                CloseCode = 1006
	CloseCode_CLOSE_CODE_UNAUTHORIZED          CloseCode = 4401
	CloseCode_CLOSE_CODE_NOTFOUND              CloseCode = 4404
	CloseCode_CLOSE_CODE_CLIENT_USER_REQUESTED CloseCode = 4100
	CloseCode_CLOSE_CODE_ROOM_EXPIRED          CloseCode = 4001
)

// Enum value maps for CloseCode.
var (
	CloseCode_name = map[int32]string{
		0:    "CLOSE_CODE_UNSPECIFIED",
		1006: "CLOSE_CODE_NORMAL",
		4401: "CLOSE_CODE_UNAUTHORIZED",
		4404: "CLOSE_CODE_NOTFOUND",
		4100: "CLOSE_CODE_CLIENT_USER_REQUESTED",
		4001: "CLOSE_CODE_ROOM_EXPIRED",
	}
	CloseCode_value = map[string]int32{
		"CLOSE_CODE_UNSPECIFIED":           0,
		"CLOSE_CODE_NORMAL":                1006,
		"CLOSE_CODE_UNAUTHORIZED":          4401,
		"CLOSE_CODE_NOTFOUND":              4404,
		"CLOSE_CODE_CLIENT_USER_REQUESTED": 4100,
		"CLOSE_CODE_ROOM_EXPIRED":          4001,
	}
)

func (x CloseCode) Enum() *CloseCode {
	p := new(CloseCode)
	*p = x
	return p
}

func (x CloseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_Swifteams_proto_enumTypes[7].Descriptor()
}

func (CloseCode) Type() protoreflect.EnumType {
	return &file_Swifteams_proto_enumTypes[7]
}

func (x CloseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloseCode.Descriptor instead.
func (CloseCode) EnumDescriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{7}
}

// SERVER
type ServerMessageType int32

const (
	ServerMessageType_SERVER_MESSAGE_UNSPECIFIED ServerMessageType = 0
	ServerMessageType_RELAY                      ServerMessageType = 1
)

// Enum value maps for ServerMessageType.
var (
	ServerMessageType_name = map[int32]string{
		0: "SERVER_MESSAGE_UNSPECIFIED",
		1: "RELAY",
	}
	ServerMessageType_value = map[string]int32{
		"SERVER_MESSAGE_UNSPECIFIED": 0,
		"RELAY":                      1,
	}
)

func (x ServerMessageType) Enum() *ServerMessageType {
	p := new(ServerMessageType)
	*p = x
	return p
}

func (x ServerMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_Swifteams_proto_enumTypes[8].Descriptor()
}

func (ServerMessageType) Type() protoreflect.EnumType {
	return &file_Swifteams_proto_enumTypes[8]
}

func (x ServerMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerMessageType.Descriptor instead.
func (ServerMessageType) EnumDescriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{8}
}

// ROOM
type RoomType int32

const (
	RoomType_ROOM_TYPE_UNSPECIFIED RoomType = 0
	RoomType_STANDARD              RoomType = 1
	RoomType_FREE                  RoomType = 2
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "ROOM_TYPE_UNSPECIFIED",
		1: "STANDARD",
		2: "FREE",
	}
	RoomType_value = map[string]int32{
		"ROOM_TYPE_UNSPECIFIED": 0,
		"STANDARD":              1,
		"FREE":                  2,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_Swifteams_proto_enumTypes[9].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_Swifteams_proto_enumTypes[9]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{9}
}

type Coordinates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Swifteams_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_Swifteams_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinates) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coordinates) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// PLUGINS
type PluginDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description  string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Version      string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Dependencies []string `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
}

func (x *PluginDefinition) Reset() {
	*x = PluginDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Swifteams_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginDefinition) ProtoMessage() {}

func (x *PluginDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_Swifteams_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginDefinition.ProtoReflect.Descriptor instead.
func (*PluginDefinition) Descriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{1}
}

func (x *PluginDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginDefinition) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginDefinition) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type PluginStoreDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members map[string]StoreMemberType `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=StoreMemberType"`
}

func (x *PluginStoreDefinition) Reset() {
	*x = PluginStoreDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Swifteams_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginStoreDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStoreDefinition) ProtoMessage() {}

func (x *PluginStoreDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_Swifteams_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStoreDefinition.ProtoReflect.Descriptor instead.
func (*PluginStoreDefinition) Descriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{2}
}

func (x *PluginStoreDefinition) GetMembers() map[string]StoreMemberType {
	if x != nil {
		return x.Members
	}
	return nil
}

type PluginManifest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ManifestVersion uint32                            `protobuf:"varint,1,opt,name=manifest_version,json=manifestVersion,proto3" json:"manifest_version,omitempty"`
	Plugin          *PluginDefinition                 `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Store           map[string]*PluginStoreDefinition `protobuf:"bytes,3,rep,name=store,proto3" json:"store,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Swifteams_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_Swifteams_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{3}
}

func (x *PluginManifest) GetManifestVersion() uint32 {
	if x != nil {
		return x.ManifestVersion
	}
	return 0
}

func (x *PluginManifest) GetPlugin() *PluginDefinition {
	if x != nil {
		return x.Plugin
	}
	return nil
}

func (x *PluginManifest) GetStore() map[string]*PluginStoreDefinition {
	if x != nil {
		return x.Store
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionType  UserSubscriptionType `protobuf:"varint,1,opt,name=subscriptionType,proto3,enum=UserSubscriptionType" json:"subscriptionType,omitempty"`
	Id                uint64               `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	PreferredNickname string               `protobuf:"bytes,2,opt,name=preferredNickname,proto3" json:"preferredNickname,omitempty"`
	Email             string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FirstName         string               `protobuf:"bytes,6,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName          string               `protobuf:"bytes,7,opt,name=lastName,proto3" json:"lastName,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Swifteams_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_Swifteams_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetSubscriptionType() UserSubscriptionType {
	if x != nil {
		return x.SubscriptionType
	}
	return UserSubscriptionType_USER_SUBSCRIPTION_UNSPECIFIED
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetPreferredNickname() string {
	if x != nil {
		return x.PreferredNickname
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

// POINTER
type Pointer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointerType PointerType  `protobuf:"varint,1,opt,name=pointerType,proto3,enum=PointerType" json:"pointerType,omitempty"`
	Coordinates *Coordinates `protobuf:"bytes,2,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *Pointer) Reset() {
	*x = Pointer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Swifteams_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pointer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pointer) ProtoMessage() {}

func (x *Pointer) ProtoReflect() protoreflect.Message {
	mi := &file_Swifteams_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pointer.ProtoReflect.Descriptor instead.
func (*Pointer) Descriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{5}
}

func (x *Pointer) GetPointerType() PointerType {
	if x != nil {
		return x.PointerType
	}
	return PointerType_POINTER_TYPE_UNSPECIFIED
}

func (x *Pointer) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type PointerCollection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pointers []*Pointer `protobuf:"bytes,1,rep,name=pointers,proto3" json:"pointers,omitempty"`
}

func (x *PointerCollection) Reset() {
	*x = PointerCollection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Swifteams_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PointerCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointerCollection) ProtoMessage() {}

func (x *PointerCollection) ProtoReflect() protoreflect.Message {
	mi := &file_Swifteams_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointerCollection.ProtoReflect.Descriptor instead.
func (*PointerCollection) Descriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{6}
}

func (x *PointerCollection) GetPointers() []*Pointer {
	if x != nil {
		return x.Pointers
	}
	return nil
}

type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string             `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Role     ClientRole         `protobuf:"varint,4,opt,name=role,proto3,enum=ClientRole" json:"role,omitempty"`
	Nickname string             `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Pointers *PointerCollection `protobuf:"bytes,3,opt,name=pointers,proto3" json:"pointers,omitempty"`
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Swifteams_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_Swifteams_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{7}
}

func (x *Client) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Client) GetRole() ClientRole {
	if x != nil {
		return x.Role
	}
	return ClientRole_CLIENT_ROLE_UNSPECIFIED
}

func (x *Client) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Client) GetPointers() *PointerCollection {
	if x != nil {
		return x.Pointers
	}
	return nil
}

type ClientChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ClientChatMessage) Reset() {
	*x = ClientChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Swifteams_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientChatMessage) ProtoMessage() {}

func (x *ClientChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Swifteams_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientChatMessage.ProtoReflect.Descriptor instead.
func (*ClientChatMessage) Descriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{8}
}

func (x *ClientChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Type      ClientMessageType      `protobuf:"varint,2,opt,name=type,proto3,enum=ClientMessageType" json:"type,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are assignable to Data:
	//
	//	*ClientMessage_Nickname
	//	*ClientMessage_Pointers
	//	*ClientMessage_ChatMessage
	Data isClientMessage_Data `protobuf_oneof:"data"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Swifteams_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Swifteams_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{9}
}

func (x *ClientMessage) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClientMessage) GetType() ClientMessageType {
	if x != nil {
		return x.Type
	}
	return ClientMessageType_CLIENT_MESSAGE_TYPE_UNSPECIFIED
}

func (x *ClientMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (m *ClientMessage) GetData() isClientMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *ClientMessage) GetNickname() string {
	if x, ok := x.GetData().(*ClientMessage_Nickname); ok {
		return x.Nickname
	}
	return ""
}

func (x *ClientMessage) GetPointers() *PointerCollection {
	if x, ok := x.GetData().(*ClientMessage_Pointers); ok {
		return x.Pointers
	}
	return nil
}

func (x *ClientMessage) GetChatMessage() *ClientChatMessage {
	if x, ok := x.GetData().(*ClientMessage_ChatMessage); ok {
		return x.ChatMessage
	}
	return nil
}

type isClientMessage_Data interface {
	isClientMessage_Data()
}

type ClientMessage_Nickname struct {
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3,oneof"`
}

type ClientMessage_Pointers struct {
	Pointers *PointerCollection `protobuf:"bytes,4,opt,name=pointers,proto3,oneof"`
}

type ClientMessage_ChatMessage struct {
	ChatMessage *ClientChatMessage `protobuf:"bytes,5,opt,name=chatMessage,proto3,oneof"`
}

func (*ClientMessage_Nickname) isClientMessage_Data() {}

func (*ClientMessage_Pointers) isClientMessage_Data() {}

func (*ClientMessage_ChatMessage) isClientMessage_Data() {}

type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ServerMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=ServerMessageType" json:"type,omitempty"`
	// Types that are assignable to Message:
	//
	//	*ServerMessage_Relay
	Message isServerMessage_Message `protobuf_oneof:"message"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Swifteams_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Swifteams_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{10}
}

func (x *ServerMessage) GetType() ServerMessageType {
	if x != nil {
		return x.Type
	}
	return ServerMessageType_SERVER_MESSAGE_UNSPECIFIED
}

func (m *ServerMessage) GetMessage() isServerMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ServerMessage) GetRelay() *ClientMessage {
	if x, ok := x.GetMessage().(*ServerMessage_Relay); ok {
		return x.Relay
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_Relay struct {
	Relay *ClientMessage `protobuf:"bytes,2,opt,name=relay,proto3,oneof"`
}

func (*ServerMessage_Relay) isServerMessage_Message() {}

type RoomConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    RoomType `protobuf:"varint,3,opt,name=type,proto3,enum=RoomType" json:"type,omitempty"`
	Id      string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Expiry  uint64   `protobuf:"varint,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Plugins []string `protobuf:"bytes,4,rep,name=plugin,proto3" json:"plugin,omitempty"`
}

func (x *RoomConfiguration) Reset() {
	*x = RoomConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Swifteams_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomConfiguration) ProtoMessage() {}

func (x *RoomConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_Swifteams_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomConfiguration.ProtoReflect.Descriptor instead.
func (*RoomConfiguration) Descriptor() ([]byte, []int) {
	return file_Swifteams_proto_rawDescGZIP(), []int{11}
}

func (x *RoomConfiguration) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *RoomConfiguration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomConfiguration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomConfiguration) GetExpiry() uint64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *RoomConfiguration) GetPlugins() []string {
	if x != nil {
		return x.Plugins
	}
	return nil
}

var File_Swifteams_proto protoreflect.FileDescriptor

var file_Swifteams_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x53, 0x77, 0x69, 0x66, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0b, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x73, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x22, 0x86, 0x01,
	0x0a, 0x10, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x15, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x3d, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x1a,
	0x4c, 0x0a, 0x0c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x10, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xea, 0x01,
	0x0a, 0x0e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74,
	0x12, 0x29, 0x0a, 0x10, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x6d, 0x61, 0x6e, 0x69,
	0x66, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x06, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4d, 0x61,
	0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x1a, 0x50, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xd7, 0x01, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x10, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x72, 0x65, 0x64, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x11, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x4e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x69, 0x0a, 0x07, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x12,
	0x2e, 0x0a, 0x0b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x2e, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x22,
	0x39, 0x0a, 0x11, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x08, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x08, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x06, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x22, 0x99, 0x02, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x1c, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a,
	0x08, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x36, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x6a, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x72, 0x65, 0x6c, 0x61,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x6c, 0x61, 0x79,
	0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x11,
	0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x09, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2a, 0x76, 0x0a, 0x0b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a,
	0x13, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x55,
	0x52, 0x53, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x45,
	0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x4f, 0x55, 0x43, 0x48, 0x10, 0x03, 0x2a, 0x77,
	0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52,
	0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x4f, 0x4f, 0x4c, 0x45, 0x41, 0x4e, 0x10, 0x05, 0x12, 0x0d,
	0x0a, 0x09, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x54, 0x41, 0x4d, 0x50, 0x10, 0x06, 0x12, 0x0e, 0x0a,
	0x0a, 0x43, 0x4f, 0x4f, 0x52, 0x44, 0x49, 0x4e, 0x41, 0x54, 0x45, 0x10, 0x03, 0x12, 0x08, 0x0a,
	0x04, 0x55, 0x53, 0x45, 0x52, 0x10, 0x04, 0x2a, 0x4d, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x45, 0x52, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x48, 0x4f, 0x53, 0x54, 0x10, 0x03, 0x2a, 0x5a, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50,
	0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b,
	0x0a, 0x17, 0x50, 0x45, 0x52, 0x53, 0x49, 0x53, 0x54, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x52, 0x45, 0x46, 0x45, 0x52, 0x52,
	0x45, 0x44, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x51, 0x55, 0x49, 0x52, 0x45, 0x44,
	0x10, 0x03, 0x2a, 0x74, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x1d, 0x55, 0x53,
	0x45, 0x52, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a,
	0x16, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x50, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x46, 0x52, 0x45, 0x45, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x55, 0x53, 0x45,
	0x52, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x50,
	0x52, 0x45, 0x4d, 0x49, 0x55, 0x4d, 0x10, 0x02, 0x2a, 0x56, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54,
	0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0e,
	0x0a, 0x0a, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x4f, 0x57, 0x4e, 0x45, 0x52, 0x10, 0x02, 0x12, 0x10,
	0x0a, 0x0c, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x03,
	0x2a, 0x74, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x1f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f,
	0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x50,
	0x44, 0x41, 0x54, 0x45, 0x5f, 0x4e, 0x49, 0x43, 0x4b, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x01, 0x12,
	0x13, 0x0a, 0x0f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x45,
	0x52, 0x53, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x4d, 0x45, 0x53,
	0x53, 0x41, 0x47, 0x45, 0x10, 0x03, 0x2a, 0xbc, 0x01, 0x0a, 0x09, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x43, 0x4f,
	0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x16, 0x0a, 0x11, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4e,
	0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0xee, 0x07, 0x12, 0x1c, 0x0a, 0x17, 0x43, 0x4c, 0x4f, 0x53,
	0x45, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49,
	0x5a, 0x45, 0x44, 0x10, 0xb1, 0x22, 0x12, 0x18, 0x0a, 0x13, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0xb4, 0x22,
	0x12, 0x25, 0x0a, 0x20, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x43,
	0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45,
	0x53, 0x54, 0x45, 0x44, 0x10, 0x84, 0x20, 0x12, 0x1c, 0x0a, 0x17, 0x43, 0x4c, 0x4f, 0x53, 0x45,
	0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52,
	0x45, 0x44, 0x10, 0xa1, 0x1f, 0x2a, 0x3e, 0x0a, 0x11, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x45,
	0x52, 0x56, 0x45, 0x52, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45,
	0x4c, 0x41, 0x59, 0x10, 0x01, 0x2a, 0x3d, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x53, 0x54, 0x41, 0x4e, 0x44, 0x41, 0x52, 0x44, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x52,
	0x45, 0x45, 0x10, 0x02, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Swifteams_proto_rawDescOnce sync.Once
	file_Swifteams_proto_rawDescData = file_Swifteams_proto_rawDesc
)

func file_Swifteams_proto_rawDescGZIP() []byte {
	file_Swifteams_proto_rawDescOnce.Do(func() {
		file_Swifteams_proto_rawDescData = protoimpl.X.CompressGZIP(file_Swifteams_proto_rawDescData)
	})
	return file_Swifteams_proto_rawDescData
}

var file_Swifteams_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_Swifteams_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_Swifteams_proto_goTypes = []interface{}{
	(PointerType)(0),              // 0: PointerType
	(StoreMemberType)(0),          // 1: StoreMemberType
	(StoreAccessType)(0),          // 2: StoreAccessType
	(StorePersistenceType)(0),     // 3: StorePersistenceType
	(UserSubscriptionType)(0),     // 4: UserSubscriptionType
	(ClientRole)(0),               // 5: ClientRole
	(ClientMessageType)(0),        // 6: ClientMessageType
	(CloseCode)(0),                // 7: CloseCode
	(ServerMessageType)(0),        // 8: ServerMessageType
	(RoomType)(0),                 // 9: RoomType
	(*Coordinates)(nil),           // 10: Coordinates
	(*PluginDefinition)(nil),      // 11: PluginDefinition
	(*PluginStoreDefinition)(nil), // 12: PluginStoreDefinition
	(*PluginManifest)(nil),        // 13: PluginManifest
	(*User)(nil),                  // 14: User
	(*Pointer)(nil),               // 15: Pointer
	(*PointerCollection)(nil),     // 16: PointerCollection
	(*Client)(nil),                // 17: Client
	(*ClientChatMessage)(nil),     // 18: ClientChatMessage
	(*ClientMessage)(nil),         // 19: ClientMessage
	(*ServerMessage)(nil),         // 20: ServerMessage
	(*RoomConfiguration)(nil),     // 21: RoomConfiguration
	nil,                           // 22: PluginStoreDefinition.MembersEntry
	nil,                           // 23: PluginManifest.StoreEntry
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
}
var file_Swifteams_proto_depIdxs = []int32{
	22, // 0: PluginStoreDefinition.members:type_name -> PluginStoreDefinition.MembersEntry
	11, // 1: PluginManifest.plugin:type_name -> PluginDefinition
	23, // 2: PluginManifest.store:type_name -> PluginManifest.StoreEntry
	4,  // 3: User.subscriptionType:type_name -> UserSubscriptionType
	0,  // 4: Pointer.pointerType:type_name -> PointerType
	10, // 5: Pointer.coordinates:type_name -> Coordinates
	15, // 6: PointerCollection.pointers:type_name -> Pointer
	5,  // 7: Client.role:type_name -> ClientRole
	16, // 8: Client.pointers:type_name -> PointerCollection
	6,  // 9: ClientMessage.type:type_name -> ClientMessageType
	24, // 10: ClientMessage.timestamp:type_name -> google.protobuf.Timestamp
	16, // 11: ClientMessage.pointers:type_name -> PointerCollection
	18, // 12: ClientMessage.chatMessage:type_name -> ClientChatMessage
	8,  // 13: ServerMessage.type:type_name -> ServerMessageType
	19, // 14: ServerMessage.relay:type_name -> ClientMessage
	9,  // 15: RoomConfiguration.type:type_name -> RoomType
	1,  // 16: PluginStoreDefinition.MembersEntry.value:type_name -> StoreMemberType
	12, // 17: PluginManifest.StoreEntry.value:type_name -> PluginStoreDefinition
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_Swifteams_proto_init() }
func file_Swifteams_proto_init() {
	if File_Swifteams_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Swifteams_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Swifteams_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Swifteams_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginStoreDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Swifteams_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginManifest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Swifteams_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Swifteams_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pointer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Swifteams_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PointerCollection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Swifteams_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Swifteams_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Swifteams_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Swifteams_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Swifteams_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_Swifteams_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*ClientMessage_Nickname)(nil),
		(*ClientMessage_Pointers)(nil),
		(*ClientMessage_ChatMessage)(nil),
	}
	file_Swifteams_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*ServerMessage_Relay)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Swifteams_proto_rawDesc,
			NumEnums:      10,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Swifteams_proto_goTypes,
		DependencyIndexes: file_Swifteams_proto_depIdxs,
		EnumInfos:         file_Swifteams_proto_enumTypes,
		MessageInfos:      file_Swifteams_proto_msgTypes,
	}.Build()
	File_Swifteams_proto = out.File
	file_Swifteams_proto_rawDesc = nil
	file_Swifteams_proto_goTypes = nil
	file_Swifteams_proto_depIdxs = nil
}
