/*
 * Generated by the protocol buffer compiler.  DO NOT EDIT! 
 */
/*
 * Generated from: Connection.proto 
 */

#ifndef PROTOBUF_C_Connection_2eproto__INCLUDED
#define PROTOBUF_C_Connection_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS
#if PROTOBUF_C_VERSION_NUMBER < 1003000
#error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
#error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif
    /*
     * --- enums --- 
     */
    typedef enum _CloseCode {
	CLOSE_CODE__CLOSE_CODE_UNSPECIFIED = 0,
	CLOSE_CODE__CLOSE_CODE_NORMAL = 1006,
	CLOSE_CODE__CLOSE_CODE_UNAUTHORIZED = 4401,
	CLOSE_CODE__CLOSE_CODE_NOTFOUND = 4404,
	CLOSE_CODE__CLOSE_CODE_CLIENT_USER_REQUESTED = 4100,
	CLOSE_CODE__CLOSE_CODE_ROOM_EXPIRED = 4001 PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CLOSE_CODE)
} CloseCode;

/*
 * --- messages --- 
 */

/*
 * --- per-message closures --- 
 */

/*
 * --- services --- 
 */

/*
 * --- descriptors --- 
 */

extern const ProtobufCEnumDescriptor close_code__descriptor;

PROTOBUF_C__END_DECLS
#endif				/* PROTOBUF_C_Connection_2eproto__INCLUDED 
				 */
