/*
 * Generated by the protocol buffer compiler.  DO NOT EDIT! 
 */
/*
 * Generated from: Server.proto 
 */

/*
 * Do not generate deprecated warnings for self 
 */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Server.pb-c.h"
void server_message__init(ServerMessage *message)
{
	static const ServerMessage init_value = SERVER_MESSAGE__INIT;
	*message = init_value;
}

size_t server_message__get_packed_size(const ServerMessage *message)
{
	assert(message->base.descriptor == &server_message__descriptor);
	return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}

size_t server_message__pack(const ServerMessage *message, uint8_t *out)
{
	assert(message->base.descriptor == &server_message__descriptor);
	return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}

size_t server_message__pack_to_buffer(const ServerMessage *message, ProtobufCBuffer *buffer)
{
	assert(message->base.descriptor == &server_message__descriptor);
	return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)
						 message, buffer);
}

ServerMessage *server_message__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
{
	return (ServerMessage *)
	    protobuf_c_message_unpack(&server_message__descriptor, allocator, len, data);
}

void server_message__free_unpacked(ServerMessage *message, ProtobufCAllocator *allocator)
{
	if (!message)
		return;
	assert(message->base.descriptor == &server_message__descriptor);
	protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

static const ProtobufCFieldDescriptor server_message__field_descriptors[2]
    = {
	{
	 "type",
	 1,
	 PROTOBUF_C_LABEL_NONE,
	 PROTOBUF_C_TYPE_ENUM,
	 0,			/* quantifier_offset */
	 offsetof(ServerMessage, type),
	 &server_message_type__descriptor,
	 NULL,
	 0,			/* flags */
	 0, NULL, NULL		/* reserved1,reserved2, etc */
	 },
	{
	 "relay",
	 2,
	 PROTOBUF_C_LABEL_NONE,
	 PROTOBUF_C_TYPE_MESSAGE,
	 offsetof(ServerMessage, message_case),
	 offsetof(ServerMessage, relay),
	 &client_message__descriptor,
	 NULL,
	 0 | PROTOBUF_C_FIELD_FLAG_ONEOF,	/* flags */
	 0, NULL, NULL		/* reserved1,reserved2, etc */
	 },
};

static const unsigned server_message__field_indices_by_name[] = {
	1,			/* field[1] = relay */
	0,			/* field[0] = type */
};

static const ProtobufCIntRange server_message__number_ranges[1 + 1] = {
	{1, 0},
	{0, 2}
};

const ProtobufCMessageDescriptor server_message__descriptor = {
	PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
	"ServerMessage",
	"ServerMessage",
	"ServerMessage",
	"",
	sizeof(ServerMessage),
	2,
	server_message__field_descriptors,
	server_message__field_indices_by_name,
	1, server_message__number_ranges,
	(ProtobufCMessageInit) server_message__init,
	NULL, NULL, NULL	/* reserved[123] */
};

static const ProtobufCEnumValue server_message_type__enum_values_by_number[2]
    = {
	{"SERVER_MESSAGE_UNSPECIFIED",
	 "SERVER_MESSAGE_TYPE__SERVER_MESSAGE_UNSPECIFIED", 0},
	{"RELAY", "SERVER_MESSAGE_TYPE__RELAY", 1},
};

static const ProtobufCIntRange server_message_type__value_ranges[] = {
	{0, 0}, {0, 2}
};

static const ProtobufCEnumValueIndex server_message_type__enum_values_by_name[2] = {
	{"RELAY", 1},
	{"SERVER_MESSAGE_UNSPECIFIED", 0},
};

const ProtobufCEnumDescriptor server_message_type__descriptor = {
	PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
	"ServerMessageType",
	"ServerMessageType",
	"ServerMessageType",
	"",
	2,
	server_message_type__enum_values_by_number,
	2,
	server_message_type__enum_values_by_name,
	1,
	server_message_type__value_ranges,
	NULL, NULL, NULL, NULL	/* reserved[1234] */
};
