/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Swifteams.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Swifteams.pb-c.h"
void   coordinates__init
                     (Coordinates         *message)
{
  static const Coordinates init_value = COORDINATES__INIT;
  *message = init_value;
}
size_t coordinates__get_packed_size
                     (const Coordinates *message)
{
  assert(message->base.descriptor == &coordinates__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t coordinates__pack
                     (const Coordinates *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &coordinates__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t coordinates__pack_to_buffer
                     (const Coordinates *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &coordinates__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Coordinates *
       coordinates__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Coordinates *)
     protobuf_c_message_unpack (&coordinates__descriptor,
                                allocator, len, data);
}
void   coordinates__free_unpacked
                     (Coordinates *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &coordinates__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plugin_definition__init
                     (PluginDefinition         *message)
{
  static const PluginDefinition init_value = PLUGIN_DEFINITION__INIT;
  *message = init_value;
}
size_t plugin_definition__get_packed_size
                     (const PluginDefinition *message)
{
  assert(message->base.descriptor == &plugin_definition__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plugin_definition__pack
                     (const PluginDefinition *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plugin_definition__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plugin_definition__pack_to_buffer
                     (const PluginDefinition *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plugin_definition__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PluginDefinition *
       plugin_definition__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PluginDefinition *)
     protobuf_c_message_unpack (&plugin_definition__descriptor,
                                allocator, len, data);
}
void   plugin_definition__free_unpacked
                     (PluginDefinition *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plugin_definition__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plugin_store_definition__members_entry__init
                     (PluginStoreDefinition__MembersEntry         *message)
{
  static const PluginStoreDefinition__MembersEntry init_value = PLUGIN_STORE_DEFINITION__MEMBERS_ENTRY__INIT;
  *message = init_value;
}
void   plugin_store_definition__init
                     (PluginStoreDefinition         *message)
{
  static const PluginStoreDefinition init_value = PLUGIN_STORE_DEFINITION__INIT;
  *message = init_value;
}
size_t plugin_store_definition__get_packed_size
                     (const PluginStoreDefinition *message)
{
  assert(message->base.descriptor == &plugin_store_definition__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plugin_store_definition__pack
                     (const PluginStoreDefinition *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plugin_store_definition__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plugin_store_definition__pack_to_buffer
                     (const PluginStoreDefinition *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plugin_store_definition__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PluginStoreDefinition *
       plugin_store_definition__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PluginStoreDefinition *)
     protobuf_c_message_unpack (&plugin_store_definition__descriptor,
                                allocator, len, data);
}
void   plugin_store_definition__free_unpacked
                     (PluginStoreDefinition *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plugin_store_definition__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plugin_manifest__store_entry__init
                     (PluginManifest__StoreEntry         *message)
{
  static const PluginManifest__StoreEntry init_value = PLUGIN_MANIFEST__STORE_ENTRY__INIT;
  *message = init_value;
}
void   plugin_manifest__init
                     (PluginManifest         *message)
{
  static const PluginManifest init_value = PLUGIN_MANIFEST__INIT;
  *message = init_value;
}
size_t plugin_manifest__get_packed_size
                     (const PluginManifest *message)
{
  assert(message->base.descriptor == &plugin_manifest__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plugin_manifest__pack
                     (const PluginManifest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plugin_manifest__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plugin_manifest__pack_to_buffer
                     (const PluginManifest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plugin_manifest__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PluginManifest *
       plugin_manifest__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PluginManifest *)
     protobuf_c_message_unpack (&plugin_manifest__descriptor,
                                allocator, len, data);
}
void   plugin_manifest__free_unpacked
                     (PluginManifest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plugin_manifest__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   user__init
                     (User         *message)
{
  static const User init_value = USER__INIT;
  *message = init_value;
}
size_t user__get_packed_size
                     (const User *message)
{
  assert(message->base.descriptor == &user__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user__pack
                     (const User *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &user__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user__pack_to_buffer
                     (const User *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &user__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
User *
       user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (User *)
     protobuf_c_message_unpack (&user__descriptor,
                                allocator, len, data);
}
void   user__free_unpacked
                     (User *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &user__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pointer__init
                     (Pointer         *message)
{
  static const Pointer init_value = POINTER__INIT;
  *message = init_value;
}
size_t pointer__get_packed_size
                     (const Pointer *message)
{
  assert(message->base.descriptor == &pointer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pointer__pack
                     (const Pointer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pointer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pointer__pack_to_buffer
                     (const Pointer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pointer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pointer *
       pointer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pointer *)
     protobuf_c_message_unpack (&pointer__descriptor,
                                allocator, len, data);
}
void   pointer__free_unpacked
                     (Pointer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pointer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pointer_collection__init
                     (PointerCollection         *message)
{
  static const PointerCollection init_value = POINTER_COLLECTION__INIT;
  *message = init_value;
}
size_t pointer_collection__get_packed_size
                     (const PointerCollection *message)
{
  assert(message->base.descriptor == &pointer_collection__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pointer_collection__pack
                     (const PointerCollection *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pointer_collection__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pointer_collection__pack_to_buffer
                     (const PointerCollection *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pointer_collection__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PointerCollection *
       pointer_collection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PointerCollection *)
     protobuf_c_message_unpack (&pointer_collection__descriptor,
                                allocator, len, data);
}
void   pointer_collection__free_unpacked
                     (PointerCollection *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pointer_collection__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client__init
                     (Client         *message)
{
  static const Client init_value = CLIENT__INIT;
  *message = init_value;
}
size_t client__get_packed_size
                     (const Client *message)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client__pack
                     (const Client *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client__pack_to_buffer
                     (const Client *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Client *
       client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Client *)
     protobuf_c_message_unpack (&client__descriptor,
                                allocator, len, data);
}
void   client__free_unpacked
                     (Client *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_chat_message__init
                     (ClientChatMessage         *message)
{
  static const ClientChatMessage init_value = CLIENT_CHAT_MESSAGE__INIT;
  *message = init_value;
}
size_t client_chat_message__get_packed_size
                     (const ClientChatMessage *message)
{
  assert(message->base.descriptor == &client_chat_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_chat_message__pack
                     (const ClientChatMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_chat_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_chat_message__pack_to_buffer
                     (const ClientChatMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_chat_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientChatMessage *
       client_chat_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientChatMessage *)
     protobuf_c_message_unpack (&client_chat_message__descriptor,
                                allocator, len, data);
}
void   client_chat_message__free_unpacked
                     (ClientChatMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_chat_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_message__init
                     (ClientMessage         *message)
{
  static const ClientMessage init_value = CLIENT_MESSAGE__INIT;
  *message = init_value;
}
size_t client_message__get_packed_size
                     (const ClientMessage *message)
{
  assert(message->base.descriptor == &client_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_message__pack
                     (const ClientMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_message__pack_to_buffer
                     (const ClientMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientMessage *
       client_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientMessage *)
     protobuf_c_message_unpack (&client_message__descriptor,
                                allocator, len, data);
}
void   client_message__free_unpacked
                     (ClientMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_message__init
                     (ServerMessage         *message)
{
  static const ServerMessage init_value = SERVER_MESSAGE__INIT;
  *message = init_value;
}
size_t server_message__get_packed_size
                     (const ServerMessage *message)
{
  assert(message->base.descriptor == &server_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_message__pack
                     (const ServerMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_message__pack_to_buffer
                     (const ServerMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerMessage *
       server_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerMessage *)
     protobuf_c_message_unpack (&server_message__descriptor,
                                allocator, len, data);
}
void   server_message__free_unpacked
                     (ServerMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   room_configuration__init
                     (RoomConfiguration         *message)
{
  static const RoomConfiguration init_value = ROOM_CONFIGURATION__INIT;
  *message = init_value;
}
size_t room_configuration__get_packed_size
                     (const RoomConfiguration *message)
{
  assert(message->base.descriptor == &room_configuration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t room_configuration__pack
                     (const RoomConfiguration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &room_configuration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t room_configuration__pack_to_buffer
                     (const RoomConfiguration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &room_configuration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoomConfiguration *
       room_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoomConfiguration *)
     protobuf_c_message_unpack (&room_configuration__descriptor,
                                allocator, len, data);
}
void   room_configuration__free_unpacked
                     (RoomConfiguration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &room_configuration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor coordinates__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Coordinates, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Coordinates, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned coordinates__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange coordinates__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor coordinates__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Coordinates",
  "Coordinates",
  "Coordinates",
  "",
  sizeof(Coordinates),
  2,
  coordinates__field_descriptors,
  coordinates__field_indices_by_name,
  1,  coordinates__number_ranges,
  (ProtobufCMessageInit) coordinates__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plugin_definition__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PluginDefinition, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PluginDefinition, description),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PluginDefinition, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dependencies",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(PluginDefinition, n_dependencies),
    offsetof(PluginDefinition, dependencies),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plugin_definition__field_indices_by_name[] = {
  3,   /* field[3] = dependencies */
  1,   /* field[1] = description */
  0,   /* field[0] = name */
  2,   /* field[2] = version */
};
static const ProtobufCIntRange plugin_definition__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor plugin_definition__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PluginDefinition",
  "PluginDefinition",
  "PluginDefinition",
  "",
  sizeof(PluginDefinition),
  4,
  plugin_definition__field_descriptors,
  plugin_definition__field_indices_by_name,
  1,  plugin_definition__number_ranges,
  (ProtobufCMessageInit) plugin_definition__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plugin_store_definition__members_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PluginStoreDefinition__MembersEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(PluginStoreDefinition__MembersEntry, value),
    &store_member_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plugin_store_definition__members_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange plugin_store_definition__members_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plugin_store_definition__members_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PluginStoreDefinition.MembersEntry",
  "MembersEntry",
  "PluginStoreDefinition__MembersEntry",
  "",
  sizeof(PluginStoreDefinition__MembersEntry),
  2,
  plugin_store_definition__members_entry__field_descriptors,
  plugin_store_definition__members_entry__field_indices_by_name,
  1,  plugin_store_definition__members_entry__number_ranges,
  (ProtobufCMessageInit) plugin_store_definition__members_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plugin_store_definition__field_descriptors[1] =
{
  {
    "members",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PluginStoreDefinition, n_members),
    offsetof(PluginStoreDefinition, members),
    &plugin_store_definition__members_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plugin_store_definition__field_indices_by_name[] = {
  0,   /* field[0] = members */
};
static const ProtobufCIntRange plugin_store_definition__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor plugin_store_definition__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PluginStoreDefinition",
  "PluginStoreDefinition",
  "PluginStoreDefinition",
  "",
  sizeof(PluginStoreDefinition),
  1,
  plugin_store_definition__field_descriptors,
  plugin_store_definition__field_indices_by_name,
  1,  plugin_store_definition__number_ranges,
  (ProtobufCMessageInit) plugin_store_definition__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plugin_manifest__store_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PluginManifest__StoreEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PluginManifest__StoreEntry, value),
    &plugin_store_definition__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plugin_manifest__store_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange plugin_manifest__store_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plugin_manifest__store_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PluginManifest.StoreEntry",
  "StoreEntry",
  "PluginManifest__StoreEntry",
  "",
  sizeof(PluginManifest__StoreEntry),
  2,
  plugin_manifest__store_entry__field_descriptors,
  plugin_manifest__store_entry__field_indices_by_name,
  1,  plugin_manifest__store_entry__number_ranges,
  (ProtobufCMessageInit) plugin_manifest__store_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plugin_manifest__field_descriptors[3] =
{
  {
    "manifest_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PluginManifest, manifest_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "plugin",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PluginManifest, plugin),
    &plugin_definition__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "store",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PluginManifest, n_store),
    offsetof(PluginManifest, store),
    &plugin_manifest__store_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plugin_manifest__field_indices_by_name[] = {
  0,   /* field[0] = manifest_version */
  1,   /* field[1] = plugin */
  2,   /* field[2] = store */
};
static const ProtobufCIntRange plugin_manifest__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor plugin_manifest__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PluginManifest",
  "PluginManifest",
  "PluginManifest",
  "",
  sizeof(PluginManifest),
  3,
  plugin_manifest__field_descriptors,
  plugin_manifest__field_indices_by_name,
  1,  plugin_manifest__number_ranges,
  (ProtobufCMessageInit) plugin_manifest__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor user__field_descriptors[7] =
{
  {
    "subscriptionType",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(User, subscriptiontype),
    &user_subscription_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "preferredNickname",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, preferrednickname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "email",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, email),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(User, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firstName",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, firstname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lastName",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, lastname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "privilege",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, privilege),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user__field_indices_by_name[] = {
  2,   /* field[2] = email */
  4,   /* field[4] = firstName */
  3,   /* field[3] = id */
  5,   /* field[5] = lastName */
  1,   /* field[1] = preferredNickname */
  6,   /* field[6] = privilege */
  0,   /* field[0] = subscriptionType */
};
static const ProtobufCIntRange user__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor user__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "User",
  "User",
  "User",
  "",
  sizeof(User),
  7,
  user__field_descriptors,
  user__field_indices_by_name,
  2,  user__number_ranges,
  (ProtobufCMessageInit) user__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pointer__field_descriptors[2] =
{
  {
    "pointerType",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Pointer, pointertype),
    &pointer_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "coordinates",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pointer, coordinates),
    &coordinates__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pointer__field_indices_by_name[] = {
  1,   /* field[1] = coordinates */
  0,   /* field[0] = pointerType */
};
static const ProtobufCIntRange pointer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pointer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Pointer",
  "Pointer",
  "Pointer",
  "",
  sizeof(Pointer),
  2,
  pointer__field_descriptors,
  pointer__field_indices_by_name,
  1,  pointer__number_ranges,
  (ProtobufCMessageInit) pointer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pointer_collection__field_descriptors[1] =
{
  {
    "pointers",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PointerCollection, n_pointers),
    offsetof(PointerCollection, pointers),
    &pointer__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pointer_collection__field_indices_by_name[] = {
  0,   /* field[0] = pointers */
};
static const ProtobufCIntRange pointer_collection__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pointer_collection__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PointerCollection",
  "PointerCollection",
  "PointerCollection",
  "",
  sizeof(PointerCollection),
  1,
  pointer_collection__field_descriptors,
  pointer_collection__field_indices_by_name,
  1,  pointer_collection__number_ranges,
  (ProtobufCMessageInit) pointer_collection__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client__field_descriptors[4] =
{
  {
    "userId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Client, userid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nickname",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Client, nickname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pointers",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Client, pointers),
    &pointer_collection__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "role",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Client, role),
    &client_role__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client__field_indices_by_name[] = {
  1,   /* field[1] = nickname */
  2,   /* field[2] = pointers */
  3,   /* field[3] = role */
  0,   /* field[0] = userId */
};
static const ProtobufCIntRange client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor client__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Client",
  "Client",
  "Client",
  "",
  sizeof(Client),
  4,
  client__field_descriptors,
  client__field_indices_by_name,
  1,  client__number_ranges,
  (ProtobufCMessageInit) client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_chat_message__field_descriptors[1] =
{
  {
    "text",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ClientChatMessage, text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_chat_message__field_indices_by_name[] = {
  0,   /* field[0] = text */
};
static const ProtobufCIntRange client_chat_message__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor client_chat_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientChatMessage",
  "ClientChatMessage",
  "ClientChatMessage",
  "",
  sizeof(ClientChatMessage),
  1,
  client_chat_message__field_descriptors,
  client_chat_message__field_indices_by_name,
  1,  client_chat_message__number_ranges,
  (ProtobufCMessageInit) client_chat_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_message__field_descriptors[6] =
{
  {
    "userId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, userid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, type),
    &client_message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nickname",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ClientMessage, data_case),
    offsetof(ClientMessage, nickname),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pointers",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ClientMessage, data_case),
    offsetof(ClientMessage, pointers),
    &pointer_collection__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chatMessage",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ClientMessage, data_case),
    offsetof(ClientMessage, chatmessage),
    &client_chat_message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ClientMessage, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_message__field_indices_by_name[] = {
  4,   /* field[4] = chatMessage */
  2,   /* field[2] = nickname */
  3,   /* field[3] = pointers */
  5,   /* field[5] = timestamp */
  1,   /* field[1] = type */
  0,   /* field[0] = userId */
};
static const ProtobufCIntRange client_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor client_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientMessage",
  "ClientMessage",
  "ClientMessage",
  "",
  sizeof(ClientMessage),
  6,
  client_message__field_descriptors,
  client_message__field_indices_by_name,
  1,  client_message__number_ranges,
  (ProtobufCMessageInit) client_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_message__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ServerMessage, type),
    &server_message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relay",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ServerMessage, message_case),
    offsetof(ServerMessage, relay),
    &client_message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_message__field_indices_by_name[] = {
  1,   /* field[1] = relay */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange server_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor server_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServerMessage",
  "ServerMessage",
  "ServerMessage",
  "",
  sizeof(ServerMessage),
  2,
  server_message__field_descriptors,
  server_message__field_indices_by_name,
  1,  server_message__number_ranges,
  (ProtobufCMessageInit) server_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor room_configuration__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RoomConfiguration, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expiry",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(RoomConfiguration, expiry),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RoomConfiguration, type),
    &room_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "plugins",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(RoomConfiguration, n_plugins),
    offsetof(RoomConfiguration, plugins),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RoomConfiguration, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned room_configuration__field_indices_by_name[] = {
  1,   /* field[1] = expiry */
  0,   /* field[0] = id */
  4,   /* field[4] = name */
  3,   /* field[3] = plugins */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange room_configuration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor room_configuration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RoomConfiguration",
  "RoomConfiguration",
  "RoomConfiguration",
  "",
  sizeof(RoomConfiguration),
  5,
  room_configuration__field_descriptors,
  room_configuration__field_indices_by_name,
  1,  room_configuration__number_ranges,
  (ProtobufCMessageInit) room_configuration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue value__enum_values_by_number[1] =
{
  { "UNSPECIFIED", "VALUE__UNSPECIFIED", 0 },
};
static const ProtobufCIntRange value__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex value__enum_values_by_name[1] =
{
  { "UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor value__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Value",
  "Value",
  "Value",
  "",
  1,
  value__enum_values_by_number,
  1,
  value__enum_values_by_name,
  1,
  value__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue pointer_type__enum_values_by_number[4] =
{
  { "POINTER_TYPE_UNSPECIFIED", "POINTER_TYPE__POINTER_TYPE_UNSPECIFIED", 0 },
  { "POINTER_TYPE_POINTER", "POINTER_TYPE__POINTER_TYPE_POINTER", 1 },
  { "POINTER_TYPE_CURSOR", "POINTER_TYPE__POINTER_TYPE_CURSOR", 2 },
  { "POINTER_TYPE_TOUCH", "POINTER_TYPE__POINTER_TYPE_TOUCH", 3 },
};
static const ProtobufCIntRange pointer_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex pointer_type__enum_values_by_name[4] =
{
  { "POINTER_TYPE_CURSOR", 2 },
  { "POINTER_TYPE_POINTER", 1 },
  { "POINTER_TYPE_TOUCH", 3 },
  { "POINTER_TYPE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor pointer_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PointerType",
  "PointerType",
  "PointerType",
  "",
  4,
  pointer_type__enum_values_by_number,
  4,
  pointer_type__enum_values_by_name,
  1,
  pointer_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue store_member_type__enum_values_by_number[7] =
{
  { "MEMBER_UNSPECIFIED", "STORE_MEMBER_TYPE__MEMBER_UNSPECIFIED", 0 },
  { "STRING", "STORE_MEMBER_TYPE__STRING", 1 },
  { "NUMBER", "STORE_MEMBER_TYPE__NUMBER", 2 },
  { "COORDINATE", "STORE_MEMBER_TYPE__COORDINATE", 3 },
  { "USER", "STORE_MEMBER_TYPE__USER", 4 },
  { "BOOLEAN", "STORE_MEMBER_TYPE__BOOLEAN", 5 },
  { "TIMESTAMP", "STORE_MEMBER_TYPE__TIMESTAMP", 6 },
};
static const ProtobufCIntRange store_member_type__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex store_member_type__enum_values_by_name[7] =
{
  { "BOOLEAN", 5 },
  { "COORDINATE", 3 },
  { "MEMBER_UNSPECIFIED", 0 },
  { "NUMBER", 2 },
  { "STRING", 1 },
  { "TIMESTAMP", 6 },
  { "USER", 4 },
};
const ProtobufCEnumDescriptor store_member_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "StoreMemberType",
  "StoreMemberType",
  "StoreMemberType",
  "",
  7,
  store_member_type__enum_values_by_number,
  7,
  store_member_type__enum_values_by_name,
  1,
  store_member_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue store_access_type__enum_values_by_number[4] =
{
  { "ACCESS_UNSPECIFIED", "STORE_ACCESS_TYPE__ACCESS_UNSPECIFIED", 0 },
  { "PUBLIC", "STORE_ACCESS_TYPE__PUBLIC", 1 },
  { "PRODUCER", "STORE_ACCESS_TYPE__PRODUCER", 2 },
  { "HOST", "STORE_ACCESS_TYPE__HOST", 3 },
};
static const ProtobufCIntRange store_access_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex store_access_type__enum_values_by_name[4] =
{
  { "ACCESS_UNSPECIFIED", 0 },
  { "HOST", 3 },
  { "PRODUCER", 2 },
  { "PUBLIC", 1 },
};
const ProtobufCEnumDescriptor store_access_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "StoreAccessType",
  "StoreAccessType",
  "StoreAccessType",
  "",
  4,
  store_access_type__enum_values_by_number,
  4,
  store_access_type__enum_values_by_name,
  1,
  store_access_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue store_persistence_type__enum_values_by_number[4] =
{
  { "PERSISTENCE_UNSPECIFIED", "STORE_PERSISTENCE_TYPE__PERSISTENCE_UNSPECIFIED", 0 },
  { "NONE", "STORE_PERSISTENCE_TYPE__NONE", 1 },
  { "PREFERRED", "STORE_PERSISTENCE_TYPE__PREFERRED", 2 },
  { "REQUIRED", "STORE_PERSISTENCE_TYPE__REQUIRED", 3 },
};
static const ProtobufCIntRange store_persistence_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex store_persistence_type__enum_values_by_name[4] =
{
  { "NONE", 1 },
  { "PERSISTENCE_UNSPECIFIED", 0 },
  { "PREFERRED", 2 },
  { "REQUIRED", 3 },
};
const ProtobufCEnumDescriptor store_persistence_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "StorePersistenceType",
  "StorePersistenceType",
  "StorePersistenceType",
  "",
  4,
  store_persistence_type__enum_values_by_number,
  4,
  store_persistence_type__enum_values_by_name,
  1,
  store_persistence_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue user_subscription_type__enum_values_by_number[3] =
{
  { "USER_SUBSCRIPTION_UNSPECIFIED", "USER_SUBSCRIPTION_TYPE__USER_SUBSCRIPTION_UNSPECIFIED", 0 },
  { "USER_SUBSCRIPTION_FREE", "USER_SUBSCRIPTION_TYPE__USER_SUBSCRIPTION_FREE", 1 },
  { "USER_SUBSCRIPTION_PREMIUM", "USER_SUBSCRIPTION_TYPE__USER_SUBSCRIPTION_PREMIUM", 2 },
};
static const ProtobufCIntRange user_subscription_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex user_subscription_type__enum_values_by_name[3] =
{
  { "USER_SUBSCRIPTION_FREE", 1 },
  { "USER_SUBSCRIPTION_PREMIUM", 2 },
  { "USER_SUBSCRIPTION_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor user_subscription_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "UserSubscriptionType",
  "UserSubscriptionType",
  "UserSubscriptionType",
  "",
  3,
  user_subscription_type__enum_values_by_number,
  3,
  user_subscription_type__enum_values_by_name,
  1,
  user_subscription_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue user_privilege__enum_values_by_number[3] =
{
  { "USER_PRIVILEGE_UNSPECIFIED", "USER_PRIVILEGE__USER_PRIVILEGE_UNSPECIFIED", 0 },
  { "PRIVILEGE_STANDARD", "USER_PRIVILEGE__PRIVILEGE_STANDARD", 1 },
  { "PRIVILEGE_SUPERUSER", "USER_PRIVILEGE__PRIVILEGE_SUPERUSER", 2 },
};
static const ProtobufCIntRange user_privilege__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex user_privilege__enum_values_by_name[3] =
{
  { "PRIVILEGE_STANDARD", 1 },
  { "PRIVILEGE_SUPERUSER", 2 },
  { "USER_PRIVILEGE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor user_privilege__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "UserPrivilege",
  "UserPrivilege",
  "UserPrivilege",
  "",
  3,
  user_privilege__enum_values_by_number,
  3,
  user_privilege__enum_values_by_name,
  1,
  user_privilege__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue client_role__enum_values_by_number[4] =
{
  { "CLIENT_ROLE_UNSPECIFIED", "CLIENT_ROLE__CLIENT_ROLE_UNSPECIFIED", 0 },
  { "GUEST", "CLIENT_ROLE__GUEST", 1 },
  { "ROOM_OWNER", "CLIENT_ROLE__ROOM_OWNER", 2 },
  { "SERVER_ADMIN", "CLIENT_ROLE__SERVER_ADMIN", 3 },
};
static const ProtobufCIntRange client_role__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex client_role__enum_values_by_name[4] =
{
  { "CLIENT_ROLE_UNSPECIFIED", 0 },
  { "GUEST", 1 },
  { "ROOM_OWNER", 2 },
  { "SERVER_ADMIN", 3 },
};
const ProtobufCEnumDescriptor client_role__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientRole",
  "ClientRole",
  "ClientRole",
  "",
  4,
  client_role__enum_values_by_number,
  4,
  client_role__enum_values_by_name,
  1,
  client_role__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue client_message_type__enum_values_by_number[4] =
{
  { "CLIENT_MESSAGE_TYPE_UNSPECIFIED", "CLIENT_MESSAGE_TYPE__CLIENT_MESSAGE_TYPE_UNSPECIFIED", 0 },
  { "UPDATE_NICKNAME", "CLIENT_MESSAGE_TYPE__UPDATE_NICKNAME", 1 },
  { "UPDATE_POINTERS", "CLIENT_MESSAGE_TYPE__UPDATE_POINTERS", 2 },
  { "CHAT_MESSAGE", "CLIENT_MESSAGE_TYPE__CHAT_MESSAGE", 3 },
};
static const ProtobufCIntRange client_message_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex client_message_type__enum_values_by_name[4] =
{
  { "CHAT_MESSAGE", 3 },
  { "CLIENT_MESSAGE_TYPE_UNSPECIFIED", 0 },
  { "UPDATE_NICKNAME", 1 },
  { "UPDATE_POINTERS", 2 },
};
const ProtobufCEnumDescriptor client_message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientMessageType",
  "ClientMessageType",
  "ClientMessageType",
  "",
  4,
  client_message_type__enum_values_by_number,
  4,
  client_message_type__enum_values_by_name,
  1,
  client_message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue close_code__enum_values_by_number[6] =
{
  { "CLOSE_CODE_UNSPECIFIED", "CLOSE_CODE__CLOSE_CODE_UNSPECIFIED", 0 },
  { "CLOSE_CODE_NORMAL", "CLOSE_CODE__CLOSE_CODE_NORMAL", 1006 },
  { "CLOSE_CODE_ROOM_EXPIRED", "CLOSE_CODE__CLOSE_CODE_ROOM_EXPIRED", 4001 },
  { "CLOSE_CODE_CLIENT_USER_REQUESTED", "CLOSE_CODE__CLOSE_CODE_CLIENT_USER_REQUESTED", 4100 },
  { "CLOSE_CODE_UNAUTHORIZED", "CLOSE_CODE__CLOSE_CODE_UNAUTHORIZED", 4401 },
  { "CLOSE_CODE_NOTFOUND", "CLOSE_CODE__CLOSE_CODE_NOTFOUND", 4404 },
};
static const ProtobufCIntRange close_code__value_ranges[] = {
{0, 0},{1006, 1},{4001, 2},{4100, 3},{4401, 4},{4404, 5},{0, 6}
};
static const ProtobufCEnumValueIndex close_code__enum_values_by_name[6] =
{
  { "CLOSE_CODE_CLIENT_USER_REQUESTED", 3 },
  { "CLOSE_CODE_NORMAL", 1 },
  { "CLOSE_CODE_NOTFOUND", 5 },
  { "CLOSE_CODE_ROOM_EXPIRED", 2 },
  { "CLOSE_CODE_UNAUTHORIZED", 4 },
  { "CLOSE_CODE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor close_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CloseCode",
  "CloseCode",
  "CloseCode",
  "",
  6,
  close_code__enum_values_by_number,
  6,
  close_code__enum_values_by_name,
  6,
  close_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue server_message_type__enum_values_by_number[2] =
{
  { "SERVER_MESSAGE_UNSPECIFIED", "SERVER_MESSAGE_TYPE__SERVER_MESSAGE_UNSPECIFIED", 0 },
  { "RELAY", "SERVER_MESSAGE_TYPE__RELAY", 1 },
};
static const ProtobufCIntRange server_message_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex server_message_type__enum_values_by_name[2] =
{
  { "RELAY", 1 },
  { "SERVER_MESSAGE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor server_message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ServerMessageType",
  "ServerMessageType",
  "ServerMessageType",
  "",
  2,
  server_message_type__enum_values_by_number,
  2,
  server_message_type__enum_values_by_name,
  1,
  server_message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue room_type__enum_values_by_number[3] =
{
  { "ROOM_TYPE_UNSPECIFIED", "ROOM_TYPE__ROOM_TYPE_UNSPECIFIED", 0 },
  { "STANDARD", "ROOM_TYPE__STANDARD", 1 },
  { "FREE", "ROOM_TYPE__FREE", 2 },
};
static const ProtobufCIntRange room_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex room_type__enum_values_by_name[3] =
{
  { "FREE", 2 },
  { "ROOM_TYPE_UNSPECIFIED", 0 },
  { "STANDARD", 1 },
};
const ProtobufCEnumDescriptor room_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "RoomType",
  "RoomType",
  "RoomType",
  "",
  3,
  room_type__enum_values_by_number,
  3,
  room_type__enum_values_by_name,
  1,
  room_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
