/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: User.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "User.pb-c.h"
void   user__init
                     (User         *message)
{
  static const User init_value = USER__INIT;
  *message = init_value;
}
size_t user__get_packed_size
                     (const User *message)
{
  assert(message->base.descriptor == &user__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user__pack
                     (const User *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &user__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user__pack_to_buffer
                     (const User *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &user__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
User *
       user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (User *)
     protobuf_c_message_unpack (&user__descriptor,
                                allocator, len, data);
}
void   user__free_unpacked
                     (User *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &user__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor user__field_descriptors[7] =
{
  {
    "subscriptionType",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(User, subscriptiontype),
    &user_subscription_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "preferredNickname",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, preferrednickname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "email",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, email),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firstName",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, firstname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lastName",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, lastname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user__field_indices_by_name[] = {
  2,   /* field[2] = email */
  5,   /* field[5] = firstName */
  4,   /* field[4] = id */
  6,   /* field[6] = lastName */
  1,   /* field[1] = preferredNickname */
  0,   /* field[0] = subscriptionType */
  3,   /* field[3] = username */
};
static const ProtobufCIntRange user__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor user__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "User",
  "User",
  "User",
  "",
  sizeof(User),
  7,
  user__field_descriptors,
  user__field_indices_by_name,
  1,  user__number_ranges,
  (ProtobufCMessageInit) user__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue user_subscription_type__enum_values_by_number[3] =
{
  { "USER_SUBSCRIPTION_UNSPECIFIED", "USER_SUBSCRIPTION_TYPE__USER_SUBSCRIPTION_UNSPECIFIED", 0 },
  { "USER_SUBSCRIPTION_FREE", "USER_SUBSCRIPTION_TYPE__USER_SUBSCRIPTION_FREE", 1 },
  { "USER_SUBSCRIPTION_PREMIUM", "USER_SUBSCRIPTION_TYPE__USER_SUBSCRIPTION_PREMIUM", 2 },
};
static const ProtobufCIntRange user_subscription_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex user_subscription_type__enum_values_by_name[3] =
{
  { "USER_SUBSCRIPTION_FREE", 1 },
  { "USER_SUBSCRIPTION_PREMIUM", 2 },
  { "USER_SUBSCRIPTION_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor user_subscription_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "UserSubscriptionType",
  "UserSubscriptionType",
  "UserSubscriptionType",
  "",
  3,
  user_subscription_type__enum_values_by_number,
  3,
  user_subscription_type__enum_values_by_name,
  1,
  user_subscription_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
